// Generated by scripts/generate-css-module-types.mjs from src/features/dashboard/DashboardPage.module.css. Do not edit.
declare const classes: {
  readonly "banner": string;
  readonly "bannerText": string;
  readonly "dayItem": string;
  readonly "dayKind": string;
  readonly "dayList": string;
  readonly "followItem": string;
  readonly "followList": string;
  readonly "followMain": string;
  readonly "followMeta": string;
  readonly "followStale": string;
  readonly "followTitle": string;
  readonly "metrics": string;
  readonly "note": string;
};
export default classes;
