// Generated by scripts/generate-css-module-types.mjs from src/features/ledger/LedgerPage.module.css. Do not edit.
declare const classes: {
  readonly "card": string;
  readonly "cardBadges": string;
  readonly "cardField": string;
  readonly "cardFields": string;
  readonly "cardLabel": string;
  readonly "cardTitle": string;
  readonly "cardValue": string;
  readonly "cards": string;
  readonly "nowrap": string;
  readonly "remark": string;
  readonly "table": string;
  readonly "tableWrap": string;
  readonly "title": string;
};
export default classes;
