// Generated by scripts/generate-css-module-types.mjs from src/components/layout/AppShell.module.css. Do not edit.
declare const classes: {
  readonly "banner": string;
  readonly "brand": string;
  readonly "header": string;
  readonly "headerAction": string;
  readonly "headerInner": string;
  readonly "main": string;
  readonly "nav": string;
  readonly "navItem": string;
  readonly "navLink": string;
  readonly "navLinkCurrent": string;
  readonly "navList": string;
  readonly "pageActions": string;
  readonly "pageDescription": string;
  readonly "pageHeader": string;
  readonly "pageHeaderText": string;
  readonly "pageTitle": string;
  readonly "split": string;
  readonly "splitAside": string;
  readonly "splitMain": string;
};
export default classes;
