// Generated by scripts/generate-css-module-types.mjs from src/features/honors/HonorsPage.module.css. Do not edit.
declare const classes: {
  readonly "field": string;
  readonly "fieldLabel": string;
  readonly "fieldValue": string;
  readonly "fieldWide": string;
  readonly "fields": string;
  readonly "grid": string;
  readonly "honorBadges": string;
  readonly "honorCard": string;
  readonly "levelLabel": string;
  readonly "levelRow": string;
  readonly "type": string;
};
export default classes;
