// Generated by scripts/generate-css-module-types.mjs from src/features/backup-restore/ImportDialog.module.css. Do not edit.
declare const classes: {
  readonly "body": string;
  readonly "details": string;
  readonly "errorList": string;
  readonly "errorTitle": string;
  readonly "file": string;
  readonly "fileHint": string;
  readonly "fileLabel": string;
  readonly "legend": string;
  readonly "list": string;
  readonly "mode": string;
  readonly "modeHint": string;
  readonly "modes": string;
  readonly "picker": string;
  readonly "preview": string;
  readonly "previewTitle": string;
  readonly "stat": string;
  readonly "statLabel": string;
  readonly "statValue": string;
  readonly "stats": string;
  readonly "truncated": string;
};
export default classes;
