// Generated by scripts/generate-css-module-types.mjs from src/app/App.module.css. Do not edit.
declare const classes: {
  readonly "errorHint": string;
  readonly "errorTitle": string;
  readonly "loading": string;
  readonly "updateBar": string;
  readonly "updateText": string;
};
export default classes;
