// Generated by scripts/generate-css-module-types.mjs from src/features/work/FilterBar.module.css. Do not edit.
declare const classes: {
  readonly "bar": string;
  readonly "chip": string;
  readonly "chips": string;
  readonly "count": string;
  readonly "more": string;
  readonly "moreOpen": string;
  readonly "row": string;
  readonly "search": string;
  readonly "searchIcon": string;
  readonly "searchWrap": string;
  readonly "secondary": string;
  readonly "select": string;
  readonly "selectLabel": string;
  readonly "selectWrap": string;
  readonly "status": string;
};
export default classes;
