// Generated by scripts/generate-css-module-types.mjs from src/features/work/MoveWorkDialog.module.css. Do not edit.
declare const classes: {
  readonly "body": string;
  readonly "count": string;
  readonly "list": string;
};
export default classes;
