// Generated by scripts/generate-css-module-types.mjs from src/features/work/ProgressPanel.module.css. Do not edit.
declare const classes: {
  readonly "add": string;
  readonly "addLabel": string;
  readonly "editor": string;
  readonly "editorActions": string;
  readonly "empty": string;
  readonly "heading": string;
  readonly "item": string;
  readonly "itemActions": string;
  readonly "itemHead": string;
  readonly "itemNote": string;
  readonly "itemTime": string;
  readonly "panel": string;
  readonly "textarea": string;
  readonly "timeline": string;
};
export default classes;
