// Generated by scripts/generate-css-module-types.mjs from src/features/work/TaskStructure.module.css. Do not edit.
declare const classes: {
  readonly "actions": string;
  readonly "children": string;
  readonly "context": string;
  readonly "contextTag": string;
  readonly "disclosure": string;
  readonly "disclosureSpacer": string;
  readonly "item": string;
  readonly "level": string;
  readonly "meta": string;
  readonly "metaAlert": string;
  readonly "metaNote": string;
  readonly "node": string;
  readonly "overdue": string;
  readonly "title": string;
  readonly "tree": string;
};
export default classes;
