// Generated by scripts/generate-css-module-types.mjs from src/features/work/WorkCard.module.css. Do not edit.
declare const classes: {
  readonly "actions": string;
  readonly "badges": string;
  readonly "body": string;
  readonly "card": string;
  readonly "chevronOpen": string;
  readonly "detail": string;
  readonly "detailGrid": string;
  readonly "detailLabel": string;
  readonly "detailValue": string;
  readonly "detailWide": string;
  readonly "disclosure": string;
  readonly "head": string;
  readonly "headMain": string;
  readonly "meta": string;
  readonly "metaItem": string;
  readonly "metaLabel": string;
  readonly "metaValue": string;
  readonly "overdue": string;
  readonly "title": string;
};
export default classes;
