// Generated by scripts/generate-css-module-types.mjs from src/features/work/WorkPage.module.css. Do not edit.
declare const classes: {
  readonly "list": string;
  readonly "more": string;
};
export default classes;
