// Generated by scripts/generate-css-module-types.mjs from src/features/work/WorkCard.module.css. Do not edit.
declare const classes: {
  readonly "actions": string;
  readonly "body": string;
  readonly "chevronOpen": string;
  readonly "colCategory": string;
  readonly "colChevron": string;
  readonly "colDate": string;
  readonly "colStatus": string;
  readonly "colTitle": string;
  readonly "colUnit": string;
  readonly "colVerdict": string;
  readonly "detail": string;
  readonly "detailBlock": string;
  readonly "detailGroup": string;
  readonly "detailGroupTitle": string;
  readonly "detailGroups": string;
  readonly "detailLabel": string;
  readonly "detailList": string;
  readonly "detailValue": string;
  readonly "notes": string;
  readonly "overdue": string;
  readonly "row": string;
  readonly "rowExpanded": string;
  readonly "summary": string;
  readonly "title": string;
};
export default classes;
