// Generated by scripts/generate-css-module-types.mjs from src/features/work/WorkRecordDialog.module.css. Do not edit.
declare const classes: {
  readonly "checkHint": string;
  readonly "checkLabel": string;
  readonly "checkRow": string;
  readonly "form": string;
  readonly "requiredNote": string;
  readonly "section": string;
  readonly "stack": string;
  readonly "summary": string;
};
export default classes;
