// Generated by scripts/generate-css-module-types.mjs from src/features/settings/SettingsPage.module.css. Do not edit.
declare const classes: {
  readonly "addInput": string;
  readonly "addRow": string;
  readonly "anchor": string;
  readonly "danger": string;
  readonly "grid": string;
  readonly "index": string;
  readonly "indexLink": string;
  readonly "indexList": string;
  readonly "item": string;
  readonly "itemActions": string;
  readonly "itemMeta": string;
  readonly "itemName": string;
  readonly "layout": string;
  readonly "list": string;
  readonly "note": string;
  readonly "row": string;
  readonly "sections": string;
  readonly "stat": string;
  readonly "statLabel": string;
  readonly "statRow": string;
  readonly "statValue": string;
  readonly "steps": string;
  readonly "tabs": string;
};
export default classes;
