// Generated by scripts/generate-css-module-types.mjs from src/features/calendar/MonthCalendar.module.css. Do not edit.
declare const classes: {
  readonly "calendar": string;
  readonly "cell": string;
  readonly "day": string;
  readonly "dayOutside": string;
  readonly "daySelected": string;
  readonly "dayToday": string;
  readonly "dot": string;
  readonly "dotHonor": string;
  readonly "dotWork": string;
  readonly "dots": string;
  readonly "grid": string;
  readonly "head": string;
  readonly "legend": string;
  readonly "legendHint": string;
  readonly "legendItem": string;
  readonly "title": string;
  readonly "weekday": string;
};
export default classes;
