// Generated by scripts/generate-css-module-types.mjs from src/features/groups/GroupPanel.module.css. Do not edit.
declare const classes: {
  readonly "empty": string;
  readonly "group": string;
  readonly "groupHead": string;
  readonly "groupMeta": string;
  readonly "groupName": string;
  readonly "item": string;
  readonly "itemMore": string;
  readonly "items": string;
  readonly "list": string;
};
export default classes;
