// Generated by scripts/generate-css-module-types.mjs from src/components/common/Button.module.css. Do not edit.
declare const classes: {
  readonly "button": string;
  readonly "danger": string;
  readonly "fullWidth": string;
  readonly "ghost": string;
  readonly "honor": string;
  readonly "icon": string;
  readonly "iconOnly": string;
  readonly "label": string;
  readonly "lg": string;
  readonly "md": string;
  readonly "primary": string;
  readonly "secondary": string;
  readonly "sm": string;
};
export default classes;
