// Generated by scripts/generate-css-module-types.mjs from src/components/common/Card.module.css. Do not edit.
declare const classes: {
  readonly "actions": string;
  readonly "card": string;
  readonly "description": string;
  readonly "empty": string;
  readonly "emptyAction": string;
  readonly "emptyDescription": string;
  readonly "emptyIcon": string;
  readonly "emptyTitle": string;
  readonly "header": string;
  readonly "headerText": string;
  readonly "metric": string;
  readonly "metric-alert": string;
  readonly "metric-normal": string;
  readonly "metric-positive": string;
  readonly "metricButton": string;
  readonly "metricDetail": string;
  readonly "metricLabel": string;
  readonly "metricValue": string;
  readonly "panel": string;
  readonly "title": string;
  readonly "tone-danger": string;
  readonly "tone-default": string;
  readonly "tone-info": string;
  readonly "tone-warning": string;
};
export default classes;
