// Generated by scripts/generate-css-module-types.mjs from src/components/common/ConfirmDialog.module.css. Do not edit.
declare const classes: {
  readonly "body": string;
  readonly "code": string;
  readonly "phrase": string;
  readonly "phraseHelp": string;
  readonly "phraseInput": string;
  readonly "phraseLabel": string;
};
export default classes;
