// Generated by scripts/generate-css-module-types.mjs from src/components/common/DateValueInput.module.css. Do not edit.
declare const classes: {
  readonly "control": string;
  readonly "hint": string;
  readonly "kindOption": string;
  readonly "kinds": string;
  readonly "legend": string;
  readonly "range": string;
  readonly "rangeLabel": string;
  readonly "rangePart": string;
  readonly "wrapper": string;
};
export default classes;
