// Generated by scripts/generate-css-module-types.mjs from src/components/common/Dialog.module.css. Do not edit.
declare const classes: {
  readonly "backdrop": string;
  readonly "body": string;
  readonly "close": string;
  readonly "description": string;
  readonly "footer": string;
  readonly "header": string;
  readonly "lg": string;
  readonly "md": string;
  readonly "panel": string;
  readonly "sm": string;
  readonly "title": string;
};
export default classes;
