// Generated by scripts/generate-css-module-types.mjs from src/components/common/Field.module.css. Do not edit.
declare const classes: {
  readonly "asterisk": string;
  readonly "control": string;
  readonly "error": string;
  readonly "field": string;
  readonly "group": string;
  readonly "groupBody": string;
  readonly "hint": string;
  readonly "label": string;
  readonly "legend": string;
  readonly "row": string;
};
export default classes;
