// Generated by scripts/generate-css-module-types.mjs from src/components/common/StatusBadge.module.css. Do not edit.
declare const classes: {
  readonly "badge": string;
  readonly "count": string;
  readonly "honor": string;
  readonly "longTerm": string;
  readonly "status-cancelled": string;
  readonly "status-completed": string;
  readonly "status-deferred": string;
  readonly "status-in-progress": string;
  readonly "status-todo": string;
  readonly "urgency-due-soon": string;
  readonly "urgency-due-today": string;
  readonly "urgency-none": string;
  readonly "urgency-overdue": string;
  readonly "urgency-scheduled": string;
  readonly "urgency-text-only": string;
};
export default classes;
