// Generated by scripts/generate-css-module-types.mjs from src/components/common/Toast.module.css. Do not edit.
declare const classes: {
  readonly "close": string;
  readonly "error": string;
  readonly "info": string;
  readonly "message": string;
  readonly "region": string;
  readonly "stack": string;
  readonly "success": string;
  readonly "toast": string;
};
export default classes;
