// Generated by scripts/generate-css-module-types.mjs from src/features/reports/ReportsPage.module.css. Do not edit.
declare const classes: {
  readonly "actions": string;
  readonly "breakdown": string;
  readonly "caption": string;
  readonly "controls": string;
  readonly "note": string;
  readonly "range": string;
  readonly "recordItem": string;
  readonly "recordList": string;
  readonly "recordMeta": string;
  readonly "recordTitle": string;
  readonly "summaryDetail": string;
  readonly "summaryGrid": string;
  readonly "summaryItem": string;
  readonly "summaryLabel": string;
  readonly "summaryValue": string;
  readonly "toggle": string;
  readonly "toggles": string;
};
export default classes;
